### PR TITLE
Refactor/webpack es6

### PR DESCRIPTION
**Pull request by posgarou**
It's so much happier... (`webpack -w`)

### CODE REVIEW

**Comment by jctillman** [comment]
I'm leaving the place I was working.... getting

ERROR in
./~/css-loader!./~/autoprefixer-loader!./~/sass-loader!./src/css/app.scss
Module build failed: ReferenceError: Promise is not defined

When I webpack -w.

**Comment by posgarou** [comment]
Probably that your version of node is outdated (https://github.com/webpack/css-loader/issues/144).  I downgraded to 0.10.36 and saw the same error.  (I was using 0.12.4, which is itself a bit old.)

(On the topic of node versions, you may already be familiar with it but [nvm](https://github.com/creationix/nvm) is a pretty handy tool for managing node versions.)

**Comment by posgarou** [comment]
Old being a few months ago (for 0.12.4) and January of this year (for 0.10.36), tbf.

**Comment by jctillman** [comment]
Ah, gotcha.  It's working now.

So is it normal to have a webpack and a gulp file?  I looked around and
found some ways to combine them...

Also, that didn't solve the problem re. the CSS and fading from one thing
to another.  The issue is that I want a fade out, fade in effect.  If I
make the old content disappear instantly (thus the display none) then the
fade-in works fine.  But if I try a fade out and a fade in, the content
gets stacked while one fades out and the other in.

**Comment by posgarou** [comment]
Re the gulpfile: I just forgot to delete it.  I haven't heard of combining them, but I can see how it could be useful in some situations.

Oh, sorry with the CSS.  I don't know, then.  On the plus side, it looked normal to me without the `display: none`.

If you explicitly want one to fade out and the other to fade in, maybe you could add a delay on the fade-in equal to the duration of the fade-out transition?  Let me know if you figure it out.

**Pull request merged**
